/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Sep 05 00:02:39 2018. */

#include "union.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Weather_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Weather, type, type, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Weather, start, type, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, Weather, human_start, start, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Weather, idx, human_start, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, Weather, temperature, idx, 0),
    PB_LAST_FIELD
};

const pb_field_t Meeting_fields[7] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Meeting, start, start, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Meeting, human_start, start, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, Meeting, human_end, human_start, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, Meeting, title, human_end, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, Meeting, room, title, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, Meeting, idx, room, 0),
    PB_LAST_FIELD
};

const pb_field_t Todo_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Todo, title, title, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Todo, status, title, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Todo, idx, status, 0),
    PB_LAST_FIELD
};

const pb_field_t RetrivalStatus_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, RetrivalStatus, status, status, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, RetrivalStatus, message, status, 0),
    PB_LAST_FIELD
};

const pb_field_t Time_fields[9] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Time, year, year, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Time, month, year, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Time, date, month, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Time, weekday, date, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, Time, hours, weekday, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, Time, minutes, hours, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, Time, seconds, minutes, 0),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, Time, am, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t Header_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Header, length, length, 0),
    PB_LAST_FIELD
};

const pb_field_t UnionMessage_fields[7] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, UnionMessage, state, state, &RetrivalStatus_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, meeting, state, &Meeting_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, todo, meeting, &Todo_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, weather, todo, &Weather_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, time, weather, &Time_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, UnionMessage, header, time, &Header_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UnionMessage, state) < 65536 && pb_membersize(UnionMessage, meeting) < 65536 && pb_membersize(UnionMessage, todo) < 65536 && pb_membersize(UnionMessage, weather) < 65536 && pb_membersize(UnionMessage, time) < 65536 && pb_membersize(UnionMessage, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Weather_Meeting_Todo_RetrivalStatus_Time_Header_UnionMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UnionMessage, state) < 256 && pb_membersize(UnionMessage, meeting) < 256 && pb_membersize(UnionMessage, todo) < 256 && pb_membersize(UnionMessage, weather) < 256 && pb_membersize(UnionMessage, time) < 256 && pb_membersize(UnionMessage, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Weather_Meeting_Todo_RetrivalStatus_Time_Header_UnionMessage)
#endif


/* @@protoc_insertion_point(eof) */
